### ISSUE TITLE
Test new iteration of Peak detection code

### ISSUE THREAD

**Issue by twsdbailey** [scimusmn/mud-pulse#10]

**Comment by twsdbailey** [comment]
Can we try this new code soon?

**Comment by brandonwkipp** [comment]
I think so; I just talked with Christine and she said the exhibit was gonna go back down around noon today. I can probably come down around 1pm or so to do some more testing.

**Comment by twsdbailey** [comment]
Having a simple threshold seems to work the best.  Peak detection introduces more complexity and is not reliable as written.
