### ISSUE TITLE
Configure a Win PC for exhibit prototyping

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/mud-pulse#2]

**Comment by bryankennedy** [comment]
Brandon already set this computer manually.

Next step is to get this setup with Ansible.

**Comment by bryankennedy** [comment]
Brandon will also work on getting Stele setup on the computer re: https://github.com/scimusmn/deploy-tools-ansible/issues/78

**Comment by brandonwkipp** [comment]
The PC has been setup.
