### ISSUE TITLE
As a visitor I want to see a graph of the mud pulse sensor

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/mud-pulse#4]
@brandonwkipp will talk with @twsdbailey and @eojreyem to figure out what sort of graph we want to see here.

Is this a simple X Y graph? Is it just an X value over time? Once Dave and Joe help define this, @brandonwkipp and I will talk about what graphing library to use.

**Comment by bryankennedy** [comment]
Test out using D3 or Vega as a simple graphing utility.

**Comment by brandonwkipp** [comment]
We decided to go with [chart-js](https://github.com/jerairrest/react-chartjs-2) for our graphing needs. Seems pretty robust so far.
