### ISSUE TITLE
linebreak-style compatibility with Windows

### ISSUE THREAD

**Issue by eojreyem** [scimusmn/mud-pulse#7]
As a Windows User, I want Stele to be able to handle Unix linebreak-style.

Receiving this error:
`Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

Currently have a work-around of adding this comment to the top of every file:
`/*eslint linebreak-style: ["error", "windows"]*/`

**Comment by bryankennedy** [comment]
@eojreyem, did you use https://gitforwindows.org/ to setup Git on your machine?

That's what I use on my Windows setups. During the install there is an option on how to handle line endings. See this screenshot:
https://d.pr/i/ovABot

Even if you didn't use this tool to setup git on your machine you should be able to enable the config setting I mention in that screenshot.

**Comment by eojreyem** [comment]
I can look into that.  @brandonwkipp  set up this Intel Nuc using Ansible.

**Comment by bryankennedy** [comment]
Ahh gotcha. I'll look at how we're installing that. So this isn't on your developer machine.

What software are you using to do the git clone?

**Comment by brandonwkipp** [comment]
I used git to clone it on to that machine.

**Comment by bryankennedy** [comment]
Sorry, I should have been more specific. Did you execute the git clone command via:
- the Windows cmd prompt?
- the Git Bash app?
- some Git GUI?

**Comment by brandonwkipp** [comment]
Powershell (Admin)

**Comment by eojreyem** [comment]
I've used the Git Bash app to pull changes.
I ran this via Git Bash:
`git config --global core.autocrlf true`

Would I have to pull the repo again for it to fix the issue?

**Comment by bryankennedy** [comment]
Joe, we came to the same solution at the same time. I just added an issue here:
https://github.com/scimusmn/deploy-tools-ansible/issues/85

Yes, your command should fix the issue, and yes, you will need to re-clone the repo, re-install the modules, and re run the server.

```
git clone git@github.com:scimusmn/mud-pulse.git
cd mud-pulse
yarn
yarn start
```

**Comment by bryankennedy** [comment]
@eojreyem if this fixes your issue, will you close it?

**Comment by eojreyem** [comment]
Deleted the repo, re-cloned it and followed the instructions. Doesn't seem to have solved it.
 
When I open the config file in VIM that (core.autocrlf = true) seems to be the only setting. So maybe I'm in the wrong config file?
`git config --global --edit`

I can keep trying to figure it out.

**Comment by bryankennedy** [comment]
I'll stop down at some point today to see if I can help debug.

**Comment by eojreyem** [comment]
from git Bash
`git config --global --edit`

then edit the line:
`git config --global core.autocrlf **false**`  (not true)

Then
```
git clone git@github.com:scimusmn/mud-pulse.git
cd mud-pulse
yarn
yarn start
```
